### ISSUE TITLE
Member inactivity kick list

### ISSUE THREAD

**Issue by Yofou** [geotim90/Nevini#104]
As of right now, we constantly demote people, in a clan called Lethal mob. We use Nevini as a crucial part of our member management tool. It would be awesome to see a feature where we can add a note or maybe inactivity status where we can do a quick lookup on a user to see if their away or not.

The reason for this request is due to our current system its pretty hard to loop up noted inactivity on a user, which results in people not really checking it, therefore us potentially kicking members that have said they're gonna be away for a bit.

I think this feature would be awesome to see in the future, regards -- Nathan (Clan IT Technician) & Love from lethal mob staff team

**Comment by geotim90** [comment]
How about a command that exempts a user from the activity reports until a given date?

**Comment by Yofou** [comment]
Yeah, just something where we can do a geo report on that member and maybe show us some kind of note, trick/crossfield

where it tells us that they have been noted down as on away (and maybe potentially a date when they are support to come back), so we know not to demote them if they have reached 60 days

**Comment by geotim90** [comment]
Implementation started - new commands:
* activity set away
* activity get away
* activity unset away

Reports will include this information as well
